/**
 * Bundesland (код) для городов из CITIES в index.html (cities246.json).
 * Сгенерировано: scripts/build-city-bl.cjs — не править вручную без перегенерации.
 */
(function (global) {
  'use strict';
  global.CITY_TO_BL = {
  "Aachen": "NW",
  "Aalen": "BW",
  "Achim": "NI",
  "Ahlen": "NW",
  "Albstadt": "BW",
  "Alsdorf": "NW",
  "Andernach": "RP",
  "Arnsberg": "NW",
  "Aschaffenburg": "BY",
  "Augsburg": "BY",
  "Baden-Baden": "BW",
  "Bad Homburg vor der Höhe": "HE",
  "Bad Kreuznach": "RP",
  "Bad Nauheim": "HE",
  "Bad Oeynhausen": "NW",
  "Bad Salzuflen": "NW",
  "Bad Vilbel": "HE",
  "Balingen": "BW",
  "Bamberg": "BY",
  "Barsinghausen": "NI",
  "Bayreuth": "BY",
  "Beckum": "NW",
  "Bensheim": "HE",
  "Bergisch Gladbach": "NW",
  "Berlin": "BE",
  "Bielefeld": "NW",
  "Bietigheim-Bissingen": "BW",
  "Bochum": "NW",
  "Bonn": "NW",
  "Bottrop": "NW",
  "Braunschweig": "NI",
  "Bramsche": "NI",
  "Bremen": "HB",
  "Bremerhaven": "HB",
  "Bruchsal": "BW",
  "Böblingen": "BW",
  "Buchholz in der Nordheide": "NI",
  "Burgdorf": "NI",
  "Burgwedel": "NI",
  "Buxtehude": "NI",
  "Castrop-Rauxel": "NW",
  "Chemnitz": "SN",
  "Cloppenburg": "NI",
  "Coesfeld": "NW",
  "Celle": "NI",
  "Cottbus": "BB",
  "Dachau": "BY",
  "Darmstadt": "HE",
  "Deggendorf": "BY",
  "Delbrück": "NW",
  "Delmenhorst": "NI",
  "Dessau-Roßlau": "ST",
  "Detmold": "NW",
  "Diepholz": "NI",
  "Dietzenbach": "HE",
  "Dinslaken": "NW",
  "Dorsten": "NW",
  "Dortmund": "NW",
  "Dresden": "SN",
  "Dormagen": "NW",
  "Duisburg": "NW",
  "Düren": "NW",
  "Düsseldorf": "NW",
  "Eberswalde": "BB",
  "Eisenach": "TH",
  "Emden": "NI",
  "Ennepetal": "NW",
  "Erlangen": "BY",
  "Erfurt": "TH",
  "Eschweiler": "NW",
  "Essen": "NW",
  "Esslingen am Neckar": "BW",
  "Euskirchen": "NW",
  "Falkensee": "BB",
  "Flensburg": "SH",
  "Forchheim": "BY",
  "Frechen": "NW",
  "Ahaus": "NW",
  "Frankfurt am Main": "HE",
  "Freiburg im Breisgau": "BW",
  "Freising": "BY",
  "Friedrichshafen": "BW",
  "Fulda": "HE",
  "Fürth": "BY",
  "Garbsen": "NI",
  "Gelsenkirchen": "NW",
  "Gera": "TH",
  "Germering": "BY",
  "Gevelsberg": "NW",
  "Gießen": "HE",
  "Greifswald": "MV",
  "Grevenbroich": "NW",
  "Gronau (Westf.)": "NW",
  "Gummersbach": "NW",
  "Gütersloh": "NW",
  "Göttingen": "NI",
  "Hagen": "NW",
  "Halle (Saale)": "ST",
  "Hamburg": "HH",
  "Hameln": "NI",
  "Hamm": "NW",
  "Hanau": "HE",
  "Hannover": "NI",
  "Hattingen": "NW",
  "Heidelberg": "BW",
  "Heilbronn": "BW",
  "Helmstedt": "NI",
  "Hemer": "NW",
  "Herford": "NW",
  "Herne": "NW",
  "Hildesheim": "NI",
  "Hof": "BY",
  "Hockenheim": "BW",
  "Holzminden": "NI",
  "Hohen Neuendorf": "BB",
  "Hoyerswerda": "SN",
  "Hürth": "NW",
  "Idar-Oberstein": "RP",
  "Iserlohn": "NW",
  "Ingolstadt": "BY",
  "Ilmenau": "TH",
  "Jena": "TH",
  "Kamp-Lintfort": "NW",
  "Kamen": "NW",
  "Karlsruhe": "BW",
  "Kassel": "HE",
  "Kempen": "NW",
  "Kevelaer": "NW",
  "Kehl": "BW",
  "Kerpen": "NW",
  "Kiel": "SH",
  "Kleve": "NW",
  "Koblenz": "RP",
  "Korbach": "HE",
  "Königswinter": "NW",
  "Konstanz": "BW",
  "Krefeld": "NW",
  "Köln": "NW",
  "Kempten (Allgäu)": "BY",
  "Landshut": "BY",
  "Leipzig": "SN",
  "Lemgo": "NW",
  "Leverkusen": "NW",
  "Lingen (Ems)": "NI",
  "Lippstadt": "NW",
  "Lohmar": "NW",
  "Lörrach": "BW",
  "Ludwigshafen am Rhein": "RP",
  "Ludwigsburg": "BW",
  "Lübeck": "SH",
  "Lüdenscheid": "NW",
  "Lüneburg": "NI",
  "Magdeburg": "ST",
  "Mainz": "RP",
  "Mannheim": "BW",
  "Marburg": "HE",
  "Marl": "NW",
  "Memmingen": "BY",
  "Merseburg": "ST",
  "Mettmann": "NW",
  "Minden": "NW",
  "Moers": "NW",
  "Mönchengladbach": "NW",
  "Mülheim an der Ruhr": "NW",
  "München": "BY",
  "Münster": "NW",
  "Mühlhausen": "TH",
  "Nagold": "BW",
  "Neumünster": "SH",
  "Neuss": "NW",
  "Neu-Ulm": "BY",
  "Nordhausen": "TH",
  "Norderstedt": "SH",
  "Nürnberg": "BY",
  "Nörenberg": "BY",
  "Oberhausen": "NW",
  "Offenburg": "BW",
  "Oldenburg": "NI",
  "Osnabrück": "NI",
  "Passau": "BY",
  "Paderborn": "NW",
  "Peine": "NI",
  "Pinneberg": "SH",
  "Plauen": "SN",
  "Pforzheim": "BW",
  "Potsdam": "BB",
  "Ratingen": "NW",
  "Regensburg": "BY",
  "Remscheid": "NW",
  "Recklinghausen": "NW",
  "Reutlingen": "BW",
  "Rheine": "NW",
  "Riesa": "SN",
  "Rosenheim": "BY",
  "Rostock": "MV",
  "Rüsselsheim am Main": "HE",
  "Saarbrücken": "SL",
  "Salzgitter": "NI",
  "Schwäbisch Gmünd": "BW",
  "Schwäbisch Hall": "BW",
  "Schwerte": "NW",
  "Schwerin": "MV",
  "Siegen": "NW",
  "Solingen": "NW",
  "Speyer": "RP",
  "Stade": "NI",
  "Stendal": "ST",
  "Straubing": "BY",
  "Stuttgart": "BW",
  "Suhl": "TH",
  "Trier": "RP",
  "Troisdorf": "NW",
  "Tübingen": "BW",
  "Ulm": "BW",
  "Unna": "NW",
  "Velbert": "NW",
  "Velten": "BB",
  "Viersen": "NW",
  "Villingen-Schwenningen": "BW",
  "Waiblingen": "BW",
  "Weimar": "TH",
  "Wetzlar": "HE",
  "Wiesbaden": "HE",
  "Wilhelmshaven": "NI",
  "Wismar": "MV",
  "Wolfsburg": "NI",
  "Worms": "RP",
  "Wuppertal": "NW",
  "Würzburg": "BY",
  "Wunstorf": "NI",
  "Zeitz": "ST",
  "Zwickau": "SN",
  "Zweibrücken": "RP",
  "Ellwangen (Jagst)": "BW",
  "Langen (Hessen)": "HE",
  "Lehrte": "NI",
  "Limburg an der Lahn": "HE",
  "Meppen": "NI",
  "Singen (Hohentwiel)": "BW",
  "Gladbeck": "NW",
  "Haan": "NW",
  "Heinsberg": "NW",
  "Herten": "NW",
  "Kaiserslautern": "RP",
  "Witten": "NW",
  "Radebeul": "SN"
};
})(typeof window !== 'undefined' ? window : this);
